
package frame.admin;

import connection.Koneksi;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import model.Dosen;
import util.FrameSetting;
import util.JamDigital;

/**
 *
 * @author teguh8464_
 */
public class DosenFrame extends javax.swing.JFrame {
    
    private Dosen dosen;
    private Connection con;
    private PreparedStatement ps;
    private ResultSet rs;
    private Statement st;
    private String qry;

    /**
     * Method untuk mengambil seluruh dosen
     * @param keyword
     * @return dosenList
     */
    public ArrayList<Dosen> getDosenList(String keyword) {
        ArrayList<Dosen> dosenList = new ArrayList<>();
        con = Koneksi.getKoneksi();
        qry = "SELECT * FROM dosen" + keyword;
        
        try {
            st = con.createStatement();
            rs = st.executeQuery(qry);
            while (rs.next()) {                
                dosen = new Dosen(
                        rs.getString("nip"), 
                        rs.getString("nama_dosen"),
                        rs.getString("telepon"),
                        rs.getString("alamat"));
                dosenList.add(dosen);
            }
        } catch (SQLException | NullPointerException ex) {
            System.err.println("Error getDosenList(): " + ex.getMessage());
        }
        return dosenList;
    }
    
    /**
     * Method untuk menampilkan data dosen ke tabel dosen
     */
    public void selectDosen(String keyword) {
        ArrayList<Dosen> list = getDosenList(keyword);
        DefaultTableModel model = (DefaultTableModel) tDosen.getModel();
        Object[] row = new Object[5];
        int no = 1;
        
        for (int i = 0; i < list.size(); i++) {
            row[0] = no++;
            row[1] = list.get(i).getNip();
            row[2] = list.get(i).getNama();
            row[3] = list.get(i).getTelepon();
            row[4] = list.get(i).getAlamat();
            model.addRow(row);
        }
    }
    
    /**
     * Method untuk mengatur ulang / refresh tabel dosen
     */
    public final void resetTable(String keyword) {
        DefaultTableModel model = (DefaultTableModel) tDosen.getModel();
        model.setRowCount(0);
        selectDosen(keyword);
    }
    
    /**
     * Method untuk membersihkan field
     */
    public void clearField() {
        eNip.setText("");
        eNama.setText("");
        eHp.setText("");
        eAlamat.setText("");
        eNip.setEnabled(true);
        eNip.requestFocus();
    }

    /**
     * Method untuk mengatur lebar kolom tabel dosen
     */
    public void lebarKolom(){ 
        TableColumn column;
        tDosen.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = tDosen.getColumnModel().getColumn(0); 
        column.setPreferredWidth(30);
        column = tDosen.getColumnModel().getColumn(1); 
        column.setPreferredWidth(190);
        column = tDosen.getColumnModel().getColumn(2); 
        column.setPreferredWidth(300); 
        column = tDosen.getColumnModel().getColumn(3); 
        column.setPreferredWidth(145); 
        column = tDosen.getColumnModel().getColumn(4); 
        column.setPreferredWidth(359); 
    }
    
    /**
     * Creates new form MakulFrame
     */
    public DosenFrame() {
        initComponents();
        FrameSetting.setFrame(this);
        JamDigital.getJam(lbl_jam);
        lebarKolom();
        resetTable("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bKembali = new javax.swing.JLabel();
        bLogout = new javax.swing.JLabel();
        bExit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eNip = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        eNama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        eHp = new javax.swing.JTextField();
        eAlamat = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cbCari = new javax.swing.JComboBox<>();
        eCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDosen = new javax.swing.JTable();
        lbl_jam = new javax.swing.JLabel();
        bSimpan = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bBatal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/button/back.png"))); // NOI18N
        bKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bKembaliMouseClicked(evt);
            }
        });
        getContentPane().add(bKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 70, 90));

        bLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/button/logout.png"))); // NOI18N
        bLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(bLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 70, 90));

        bExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/button/exit.png"))); // NOI18N
        bExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bExitMouseClicked(evt);
            }
        });
        getContentPane().add(bExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 90, 90));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 21)); // NOI18N
        jLabel2.setText("NIP");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        eNip.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(eNip, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 300, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 21)); // NOI18N
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        eNama.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(eNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 500, -1));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 21)); // NOI18N
        jLabel9.setText("Alamat");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 21)); // NOI18N
        jLabel5.setText("No. Telepon");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        eHp.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(eHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 300, -1));

        eAlamat.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        getContentPane().add(eAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 800, -1));

        jLabel15.setFont(new java.awt.Font("Berlin Sans FB", 0, 21)); // NOI18N
        jLabel15.setText("Cari Dosen");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, -1, -1));

        cbCari.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cbCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIP", "Nama Dosen" }));
        cbCari.setPreferredSize(new java.awt.Dimension(64, 18));
        getContentPane().add(cbCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 548, 140, 30));

        eCari.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        eCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eCariKeyPressed(evt);
            }
        });
        getContentPane().add(eCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 548, 300, -1));

        tDosen.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        tDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "NIP", "Nama Dosen", "Nomor Telepon", "Alamat"
            }
        ));
        tDosen.setGridColor(new java.awt.Color(0, 0, 0));
        tDosen.setMinimumSize(new java.awt.Dimension(100, 0));
        tDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDosenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tDosen);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 1030, 190));

        lbl_jam.setFont(new java.awt.Font("Microsoft YaHei", 1, 20)); // NOI18N
        lbl_jam.setText("Jam");
        getContentPane().add(lbl_jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        bSimpan.setBackground(new java.awt.Color(198, 210, 211));
        bSimpan.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        bSimpan.setForeground(new java.awt.Color(59, 59, 59));
        bSimpan.setText("SIMPAN");
        bSimpan.setToolTipText("");
        bSimpan.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(171, 176, 174), 2, true), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(198, 210, 211), 2)));
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(bSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 180, 40));

        bUbah.setBackground(new java.awt.Color(198, 210, 211));
        bUbah.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        bUbah.setForeground(new java.awt.Color(59, 59, 59));
        bUbah.setText("UBAH");
        bUbah.setToolTipText("");
        bUbah.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(171, 176, 174), 2, true), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(198, 210, 211), 2)));
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });
        getContentPane().add(bUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 180, 40));

        bHapus.setBackground(new java.awt.Color(198, 210, 211));
        bHapus.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        bHapus.setForeground(new java.awt.Color(59, 59, 59));
        bHapus.setText("HAPUS");
        bHapus.setToolTipText("");
        bHapus.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(171, 176, 174), 2, true), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(198, 210, 211), 2)));
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        getContentPane().add(bHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 420, 180, 40));

        bBatal.setBackground(new java.awt.Color(198, 210, 211));
        bBatal.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        bBatal.setForeground(new java.awt.Color(59, 59, 59));
        bBatal.setText("BATAL");
        bBatal.setToolTipText("");
        bBatal.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(171, 176, 174), 2, true), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(198, 210, 211), 2)));
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });
        getContentPane().add(bBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 180, 40));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel4.setText("DOSEN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bExitMouseClicked

    private void tDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDosenMouseClicked
        // TODO add your handling code here:
        eNip.setText(tDosen.getValueAt(tDosen.getSelectedRow(), 1).toString());
        eNama.setText(tDosen.getValueAt(tDosen.getSelectedRow(), 2).toString());
        eHp.setText(tDosen.getValueAt(tDosen.getSelectedRow(), 3).toString());
        eAlamat.setText(tDosen.getValueAt(tDosen.getSelectedRow(), 4).toString());
        eNama.requestFocus();
        eNip.setEnabled(false);
    }//GEN-LAST:event_tDosenMouseClicked

    private void bLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogoutMouseClicked
        // TODO add your handling code here:
        new frame.login.Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_bLogoutMouseClicked

    private void bKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bKembaliMouseClicked
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_bKembaliMouseClicked

    private void eCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eCariKeyPressed
        // TODO add your handling code here:
        String pilihCari = cbCari.getSelectedItem().toString();
        String pilihan = "";
        switch(pilihCari){
            case "NIP" :
                pilihan = "nip";
                break;
            case "Nama Dosen" :
                pilihan = "nama_dosen";
                break;
        }
        resetTable(" WHERE " + pilihan + " like '%" + eCari.getText() + "%'");
    }//GEN-LAST:event_eCariKeyPressed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        dosen = new Dosen();
        dosen.setNip(eNip.getText());
        dosen.setNama(eNama.getText());
        dosen.setTelepon(eHp.getText());
        dosen.setAlamat(eAlamat.getText());
        
        if (dosen.getNip().equalsIgnoreCase("") ||
            dosen.getNama().equalsIgnoreCase("") ||
            dosen.getTelepon().equalsIgnoreCase("") ||
            dosen.getAlamat().equalsIgnoreCase("")) 
        {
            JOptionPane.showMessageDialog(null, "Lengkapi data");
        } else {
            try {   
                con = Koneksi.getKoneksi();
                qry = "INSERT INTO dosen VALUES (?, ?, ?, ?)";

                ps = con.prepareStatement(qry);
                ps.setString(1, dosen.getNip());
                ps.setString(2, dosen.getNama());
                ps.setString(3, dosen.getTelepon());
                ps.setString(4, dosen.getAlamat());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Berhasil menyimpan data", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
                resetTable("");
                clearField();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Gagal menyimpan data: " + e.getMessage(), "Pemberitahuan", JOptionPane.ERROR_MESSAGE);
                System.err.println("gagal simpan data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        // TODO add your handling code here:
        if (eNip.getText().equals("") ||
            eNama.getText().equals("") ||
            eHp.getText().equals("") ||
            eAlamat.getText().equals("")) 
        { 
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin diubah");
        }else {
            qry = "UPDATE dosen SET nama_dosen=?, telepon=?, alamat=? WHERE nip=?";
            
            try {
                ps = con.prepareStatement(qry);
                ps.setString(1, eNama.getText());
                ps.setString(2, eHp.getText());
                ps.setString(3, eAlamat.getText());
                ps.setString(4, eNip.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Berhasil mengubah data", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
                resetTable("");
                clearField();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Gagal mengubah data: " + e.getMessage(), "Pemberitahuan", JOptionPane.ERROR_MESSAGE);
                System.err.println("gagal ubah data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_bUbahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        int pilihan = JOptionPane.showConfirmDialog(
                        null, 
                        "Yakin mau hapus", 
                        "Konfirmasi hapus", 
                        JOptionPane.YES_NO_OPTION);
        if (pilihan == 0) {
            if (eNip.getText().equals("") ||
                eNama.getText().equals("") ||
                eHp.getText().equals("") ||
                eAlamat.getText().equals("")) 
            {
                JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus");
            }else {
                try {
                    con = Koneksi.getKoneksi();
                    qry = "DELETE FROM dosen WHERE nip = ?";
                    ps = con.prepareStatement(qry);
                    ps.setString(1, eNip.getText());
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Berhasil menghapus data", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
                    resetTable("");
                    clearField();
                } catch (SQLException e) {
                   JOptionPane.showMessageDialog(null, "Gagal menghapus data: " + e.getMessage(), "Pemberitahuan", JOptionPane.ERROR_MESSAGE);
                   System.err.println("gagal hapus data: " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_bBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DosenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DosenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DosenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DosenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DosenFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBatal;
    private javax.swing.JLabel bExit;
    private javax.swing.JButton bHapus;
    private javax.swing.JLabel bKembali;
    private javax.swing.JLabel bLogout;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bUbah;
    private javax.swing.JComboBox<String> cbCari;
    private javax.swing.JTextField eAlamat;
    private javax.swing.JTextField eCari;
    private javax.swing.JTextField eHp;
    private javax.swing.JTextField eNama;
    private javax.swing.JTextField eNip;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_jam;
    private javax.swing.JTable tDosen;
    // End of variables declaration//GEN-END:variables
}
